version: '3'
services:
  postgres:
    image: "postgres:15"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: yoldi-test
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always